## Упражнения по библиотеке Numpy

In [1]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [9]:
import numpy as np

# Создаём случайный массив
arr = np.random.randint(0, 10, 10)
print("Исходный массив:", arr)

# Меняем знак у элементов между 3 и 8
mask = (arr > 3) & (arr < 8)
arr[mask] = -arr[mask]
print("Массив после изменения знака:", arr)

Исходный массив: [9 9 2 3 0 8 4 6 6 3]
Массив после изменения знака: [ 9  9  2  3  0  8 -4 -6 -6  3]


**2.** Заменить максимальный элемент случайного массива на 0

In [12]:
import numpy as np

# Создаём случайный массив
arr = np.random.randint(0, 20, 10)
print("Исходный массив:", arr)

# Заменяем максимальный элемент на 0
arr[np.argmax(arr)] = 0
print("Массив после замены максимального элемента:", arr)

Исходный массив: [ 5 11  9  1  6  1 18 13  2 12]
Массив после замены максимального элемента: [ 5 11  9  1  6  1  0 13  2 12]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [13]:
import numpy as np

# Пример двумерного массива
arr = np.array([[1, 2], [3, 4]])
print("Исходный массив:\n", arr)

# Используем np.meshgrid для создания всех комбинаций
x, y = np.meshgrid(arr[0], arr[1])
cartesian_product = np.vstack([x.ravel(), y.ravel()]).T
print("Прямое произведение:\n", cartesian_product)

Исходный массив:
 [[1 2]
 [3 4]]
Прямое произведение:
 [[1 3]
 [2 3]
 [1 4]
 [2 4]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [15]:
import numpy as np

# Создаём массивы A (8x3) и B (2x2)
A = np.random.randint(0, 10, (8, 3))
B = np.random.randint(0, 10, (2, 2))
print("Массив A:\n", A)
print("Массив B:\n", B)

# Находим строки A, содержащие элементы из каждой строки B
rows = []
for i in range(A.shape[0]):
    contains_all = True
    for b_row in B:
        if not np.all(np.isin(b_row, A[i])):
            contains_all = False
            break
    if contains_all:
        rows.append(i)

result = A[rows]
print("Строки A, содержащие элементы из каждой строки B:\n", result)

Массив A:
 [[1 0 4]
 [6 5 5]
 [1 1 2]
 [5 6 2]
 [1 7 0]
 [5 2 5]
 [2 1 4]
 [1 5 0]]
Массив B:
 [[9 4]
 [3 6]]
Строки A, содержащие элементы из каждой строки B:
 []


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [18]:
import numpy as np

# Создаём матрицу 10x3
matrix = np.random.randint(0, 5, (10, 3))
print("Исходная матрица:\n", matrix)

# Находим строки, где есть неравные значения
unequal_rows = matrix[np.apply_along_axis(lambda x: len(np.unique(x)) > 1, 1, matrix)]
print("Строки с неравными значениями:\n", unequal_rows)

Исходная матрица:
 [[3 0 0]
 [4 2 2]
 [1 2 2]
 [3 1 2]
 [2 2 3]
 [0 2 4]
 [3 3 3]
 [2 1 0]
 [4 0 0]
 [1 2 3]]
Строки с неравными значениями:
 [[3 0 0]
 [4 2 2]
 [1 2 2]
 [3 1 2]
 [2 2 3]
 [0 2 4]
 [2 1 0]
 [4 0 0]
 [1 2 3]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [19]:
import numpy as np

# Пример массива с дубликатами
matrix = np.array([[1, 2], [3, 4], [1, 2], [5, 6], [3, 4]])
print("Исходный массив:\n", matrix)

# Удаляем дубликаты
unique_matrix = np.unique(matrix, axis=0)
print("Массив после удаления дубликатов:\n", unique_matrix)

Исходный массив:
 [[1 2]
 [3 4]
 [1 2]
 [5 6]
 [3 4]]
Массив после удаления дубликатов:
 [[1 2]
 [3 4]
 [5 6]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [33]:
import numpy as np

# Пример матрицы
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])

# Без NumPy
X_list = X.tolist()
diagonal = [X_list[i][i] for i in range(min(len(X_list), len(X_list[0])))]  # Учитываем минимальную размерность
product_no_numpy = 1
for num in diagonal:
    if num != 0:
        product_no_numpy *= num
print("Произведение без NumPy:", product_no_numpy)

# С NumPy
diagonal_numpy = np.diagonal(X)
product_numpy = np.prod(diagonal_numpy[diagonal_numpy != 0])
print("Произведение с NumPy:", product_numpy)

Произведение без NumPy: 3
Произведение с NumPy: 3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [21]:
import numpy as np

# Пример векторов
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

# Без NumPy
x_list, y_list = x.tolist(), y.tolist()
x_sorted, y_sorted = sorted(x_list), sorted(y_list)
is_same_no_numpy = x_sorted == y_sorted
print("Мультимножества одинаковы (без NumPy):", is_same_no_numpy)

# С NumPy
is_same_numpy = np.array_equal(np.sort(x), np.sort(y))
print("Мультимножества одинаковы (с NumPy):", is_same_numpy)

Мультимножества одинаковы (без NumPy): True
Мультимножества одинаковы (с NumPy): True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [22]:
import numpy as np

# Пример вектора
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

# Без NumPy
x_list = x.tolist()
candidates = []
for i in range(1, len(x_list)):
    if x_list[i-1] == 0:
        candidates.append(x_list[i])
max_after_zero_no_numpy = max(candidates) if candidates else None
print("Максимальный элемент после нуля (без NumPy):", max_after_zero_no_numpy)

# С NumPy
zero_indices = np.where(x[:-1] == 0)[0]
candidates_numpy = x[zero_indices + 1]
max_after_zero_numpy = np.max(candidates_numpy) if candidates_numpy.size > 0 else None
print("Максимальный элемент после нуля (с NumPy):", max_after_zero_numpy)

Максимальный элемент после нуля (без NumPy): 5
Максимальный элемент после нуля (с NumPy): 5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [23]:
import numpy as np

# Пример вектора
x = np.array([2, 2, 2, 3, 3, 3, 5])

# Без NumPy
x_list = x.tolist()
values, counts = [], []
current_val = x_list[0]
current_count = 1
for val in x_list[1:]:
    if val == current_val:
        current_count += 1
    else:
        values.append(current_val)
        counts.append(current_count)
        current_val = val
        current_count = 1
values.append(current_val)
counts.append(current_count)
result_no_numpy = (values, counts)
print("RLE без NumPy:", result_no_numpy)

# С NumPy
changes = np.where(np.diff(x) != 0)[0] + 1
counts_numpy = np.diff(np.r_[0, changes, x.size])
values_numpy = x[np.r_[0, changes]]
result_numpy = (values_numpy, counts_numpy)
print("RLE с NumPy:", result_numpy)

RLE без NumPy: ([2, 3, 5], [3, 3, 1])
RLE с NumPy: (array([2, 3, 5]), array([3, 3, 1]))


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [24]:
import numpy as np
from scipy.spatial.distance import cdist
import time

# Пример данных
X = np.random.rand(5, 3)
Y = np.random.rand(3, 3)

# Без NumPy
X_list, Y_list = X.tolist(), Y.tolist()
distances_no_numpy = []
for x in X_list:
    row = []
    for y in Y_list:
        dist = sum((xi - yi) ** 2 for xi, yi in zip(x, y)) ** 0.5
        row.append(dist)
    distances_no_numpy.append(row)
distances_no_numpy = np.array(distances_no_numpy)
print("Евклидовы расстояния без NumPy:\n", distances_no_numpy)

# С NumPy
start_time_numpy = time.time()
distances_numpy = np.sqrt(((X[:, np.newaxis] - Y) ** 2).sum(axis=2))
numpy_time = time.time() - start_time_numpy
print("Евклидовы расстояния с NumPy:\n", distances_numpy)
print("Время с NumPy:", numpy_time)

# Сравнение с cdist
start_time_cdist = time.time()
distances_cdist = cdist(X, Y, metric='euclidean')
cdist_time = time.time() - start_time_cdist
print("Евклидовы расстояния с cdist:\n", distances_cdist)
print("Время с cdist:", cdist_time)

Евклидовы расстояния без NumPy:
 [[0.9972328  0.19436661 0.59965402]
 [0.54986388 0.4455876  0.19573324]
 [0.9000341  0.35114788 0.55473109]
 [0.77336433 0.85830707 0.55251881]
 [0.48184344 0.88058545 0.44160325]]
Евклидовы расстояния с NumPy:
 [[0.9972328  0.19436661 0.59965402]
 [0.54986388 0.4455876  0.19573324]
 [0.9000341  0.35114788 0.55473109]
 [0.77336433 0.85830707 0.55251881]
 [0.48184344 0.88058545 0.44160325]]
Время с NumPy: 0.00014019012451171875
Евклидовы расстояния с cdist:
 [[0.9972328  0.19436661 0.59965402]
 [0.54986388 0.4455876  0.19573324]
 [0.9000341  0.35114788 0.55473109]
 [0.77336433 0.85830707 0.55251881]
 [0.48184344 0.88058545 0.44160325]]
Время с cdist: 0.00011920928955078125


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [25]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [170]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [26]:
import numpy as np

calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
crunchie_calories = 60
average_calories = np.mean(calorie_stats)
difference = average_calories - crunchie_calories
print("Среднее количество калорий у конкурентов:", round(average_calories, 2))
print("Насколько выше, чем у CrunchieMunchies:", round(difference, 2))

Среднее количество калорий у конкурентов: 106.88
Насколько выше, чем у CrunchieMunchies: 46.88


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [27]:
import numpy as np

calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats_sorted = np.sort(calorie_stats)
print("Отсортированные данные:", calorie_stats_sorted)

Отсортированные данные: [ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [28]:
import numpy as np

calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
median_calories = np.median(calorie_stats)
print("Медиана калорий:", median_calories)

Медиана калорий: 110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [29]:
import numpy as np

calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
percentiles = np.percentile(calorie_stats, np.arange(0, 101, 1))
nth_percentile = np.arange(0, 101)[percentiles > 60][0]
print("Процентили:", percentiles)
print("Наименьший процентиль, превышающий 60 калорий:", nth_percentile)

Процентили: [ 50.   50.   50.   55.6  70.   70.   75.6  83.2  90.   90.   90.   90.
  90.   90.   90.   90.   91.6  99.2 100.  100.  100.  100.  100.  100.
 100.  100.  100.  100.  100.  100.  100.  100.  100.  100.  100.  100.
 100.  100.  100.  106.4 110.  110.  110.  110.  110.  110.  110.  110.
 110.  110.  110.  110.  110.  110.  110.  110.  110.  110.  110.  110.
 110.  110.  110.  110.  110.  110.  110.  110.  110.  110.  110.  110.
 110.  110.  110.  110.  110.  115.2 120.  120.  120.  120.  120.  120.
 120.  120.  120.  120.  120.  120.  124.  130.  130.  136.8 140.  140.
 140.  147.2 150.  152.4 160. ]
Наименьший процентиль, превышающий 60 калорий: 4


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [30]:
import numpy as np

calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
more_calories = np.mean(calorie_stats > 60) * 100
print("Процент хлопьев с более чем 60 калориями:", round(more_calories, 2), "%")

Процент хлопьев с более чем 60 калориями: 96.1 %


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [31]:
import numpy as np

calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_std = np.std(calorie_stats)
print("Стандартное отклонение калорий:", round(calorie_std, 2))
print("Высокое стандартное отклонение говорит о большом разбросе данных.")

Стандартное отклонение калорий: 19.36
Высокое стандартное отклонение говорит о большом разбросе данных.


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [32]:
print("""
CrunchieMunchies с 60 калориями на порцию значительно полезнее большинства конкурентов: 96% хлопьев имеют более 60 калорий, а среднее значение у конкурентов — 107 калорий. Медиана (110 калорий) подтверждает, что более половины конкурентов имеют высокую калорийность. Стандартное отклонение (19.36) показывает большой разброс, но это подчеркивает, что CrunchieMunchies стабильно ниже большинства значений. Эти данные можно использовать в маркетинге, чтобы позиционировать CrunchieMunchies как низкокалорийный и здоровый выбор.
""")


CrunchieMunchies с 60 калориями на порцию значительно полезнее большинства конкурентов: 96% хлопьев имеют более 60 калорий, а среднее значение у конкурентов — 107 калорий. Медиана (110 калорий) подтверждает, что более половины конкурентов имеют высокую калорийность. Стандартное отклонение (19.36) показывает большой разброс, но это подчеркивает, что CrunchieMunchies стабильно ниже большинства значений. Эти данные можно использовать в маркетинге, чтобы позиционировать CrunchieMunchies как низкокалорийный и здоровый выбор.

